# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seqprediction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13seqprediction.proto\x12\rseqprediction\"W\n\x0fSequenceMessage\x12\r\n\x05seqId\x18\x01 \x01(\x05\x12\x0e\n\x06treeId\x18\x02 \x01(\x05\x12\x0b\n\x03seq\x18\x03 \x03(\x05\x12\x18\n\x10runtimeInSeconds\x18\x04 \x01(\x01\"I\n\rTrainResponse\x12\x0e\n\x06treeId\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\x08\x12\x18\n\x10runtimeInSeconds\x18\x03 \x01(\x01\"6\n\x12SetNumTreesMessage\x12\x10\n\x08numTrees\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\x08\x32\xf8\x01\n\tPredictor\x12U\n\x0bsetNumTrees\x12!.seqprediction.SetNumTreesMessage\x1a!.seqprediction.SetNumTreesMessage\"\x00\x12K\n\x07predict\x12\x1e.seqprediction.SequenceMessage\x1a\x1e.seqprediction.SequenceMessage\"\x00\x12G\n\x05train\x12\x1e.seqprediction.SequenceMessage\x1a\x1c.seqprediction.TrainResponse\"\x00\x42+\n\rseqpredictionB\x12SeqPredictionProtoP\x01\xa2\x02\x03SQPb\x06proto3')



_SEQUENCEMESSAGE = DESCRIPTOR.message_types_by_name['SequenceMessage']
_TRAINRESPONSE = DESCRIPTOR.message_types_by_name['TrainResponse']
_SETNUMTREESMESSAGE = DESCRIPTOR.message_types_by_name['SetNumTreesMessage']
SequenceMessage = _reflection.GeneratedProtocolMessageType('SequenceMessage', (_message.Message,), {
  'DESCRIPTOR' : _SEQUENCEMESSAGE,
  '__module__' : 'seqprediction_pb2'
  # @@protoc_insertion_point(class_scope:seqprediction.SequenceMessage)
  })
_sym_db.RegisterMessage(SequenceMessage)

TrainResponse = _reflection.GeneratedProtocolMessageType('TrainResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINRESPONSE,
  '__module__' : 'seqprediction_pb2'
  # @@protoc_insertion_point(class_scope:seqprediction.TrainResponse)
  })
_sym_db.RegisterMessage(TrainResponse)

SetNumTreesMessage = _reflection.GeneratedProtocolMessageType('SetNumTreesMessage', (_message.Message,), {
  'DESCRIPTOR' : _SETNUMTREESMESSAGE,
  '__module__' : 'seqprediction_pb2'
  # @@protoc_insertion_point(class_scope:seqprediction.SetNumTreesMessage)
  })
_sym_db.RegisterMessage(SetNumTreesMessage)

_PREDICTOR = DESCRIPTOR.services_by_name['Predictor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rseqpredictionB\022SeqPredictionProtoP\001\242\002\003SQP'
  _SEQUENCEMESSAGE._serialized_start=38
  _SEQUENCEMESSAGE._serialized_end=125
  _TRAINRESPONSE._serialized_start=127
  _TRAINRESPONSE._serialized_end=200
  _SETNUMTREESMESSAGE._serialized_start=202
  _SETNUMTREESMESSAGE._serialized_end=256
  _PREDICTOR._serialized_start=259
  _PREDICTOR._serialized_end=507
# @@protoc_insertion_point(module_scope)
