# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

# import seqprediction_pb2 as seqprediction__pb2
from . import seqprediction_pb2 as seqprediction__pb2


class PredictorStub(object):
    """The sequence prediction service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.setNumTrees = channel.unary_unary(
                '/seqprediction.Predictor/setNumTrees',
                request_serializer=seqprediction__pb2.SetNumTreesMessage.SerializeToString,
                response_deserializer=seqprediction__pb2.SetNumTreesMessage.FromString,
                )
        self.predict = channel.unary_unary(
                '/seqprediction.Predictor/predict',
                request_serializer=seqprediction__pb2.SequenceMessage.SerializeToString,
                response_deserializer=seqprediction__pb2.SequenceMessage.FromString,
                )
        self.train = channel.unary_unary(
                '/seqprediction.Predictor/train',
                request_serializer=seqprediction__pb2.SequenceMessage.SerializeToString,
                response_deserializer=seqprediction__pb2.TrainResponse.FromString,
                )


class PredictorServicer(object):
    """The sequence prediction service definition.
    """

    def setNumTrees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'setNumTrees': grpc.unary_unary_rpc_method_handler(
                    servicer.setNumTrees,
                    request_deserializer=seqprediction__pb2.SetNumTreesMessage.FromString,
                    response_serializer=seqprediction__pb2.SetNumTreesMessage.SerializeToString,
            ),
            'predict': grpc.unary_unary_rpc_method_handler(
                    servicer.predict,
                    request_deserializer=seqprediction__pb2.SequenceMessage.FromString,
                    response_serializer=seqprediction__pb2.SequenceMessage.SerializeToString,
            ),
            'train': grpc.unary_unary_rpc_method_handler(
                    servicer.train,
                    request_deserializer=seqprediction__pb2.SequenceMessage.FromString,
                    response_serializer=seqprediction__pb2.TrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seqprediction.Predictor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Predictor(object):
    """The sequence prediction service definition.
    """

    @staticmethod
    def setNumTrees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/seqprediction.Predictor/setNumTrees',
            seqprediction__pb2.SetNumTreesMessage.SerializeToString,
            seqprediction__pb2.SetNumTreesMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/seqprediction.Predictor/predict',
            seqprediction__pb2.SequenceMessage.SerializeToString,
            seqprediction__pb2.SequenceMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/seqprediction.Predictor/train',
            seqprediction__pb2.SequenceMessage.SerializeToString,
            seqprediction__pb2.TrainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
